### ISSUE TITLE
Get_snap error

### ISSUE THREAD

**Issue by socpl425** [ReolinkCameraAPI/reolinkapipy#41]
Hi, 
Running on windows, python3.9.1 I got an issue when using get_snap. I dont have the error message handy, but it produced error on random.choices function. I changed the AppData\Roaming\Python\Python39\site-packages\reolinkapi\mixins\stream.py file:
#from random import random
import random
And now its downloading snapshot.

**Comment by Benehiko** [comment]
PR's are welcome :)

**Comment by chripell** [comment]
PR sent :-)
