### ISSUE TITLE
Make image processing dependencies optional

### ISSUE THREAD

**Issue by axlan** [ReolinkCameraAPI/reolinkapipy#45]
This is a pretty minor feature, but when I was working with this library I just needed the API interface without any of the image processing. This made it a bit overkill to install the numpy, opencv, and pillow dependencies. It would be nice if these were configured as optional dependencies https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies or there was an easy way to leave them out.

The main change other then to setup.py would be to make reolinkapi/mixins/stream.py stub itself out if the dependencies are not installed and return exceptions if invoked. Possibly like:

```
try:
    import opencv
    # Normal implementation

except ImportError:
    # Stubbed out implementation
```

**Comment by Benehiko** [comment]
Hey @axlan 

Thanks for using the library :)
Yeah unfortunately OpenCV was the best choice as a library to get RTSP streaming working. It's a headache and I've been wanting to remove the huge dependency for a while now, see #31

The changes you propose would be welcomed as it would definitely give the freedom to developers to choose what they would like :)

Just open a PR and I'll try get it merged as soon as possible ;)
