### ISSUE TITLE
requirements.txt is empty

### ISSUE THREAD

**Issue by bmxp** [ReolinkCameraAPI/reolinkapipy#58]
Would it be easier to keep ``requirements.txt`` for a while since ``pipfile`` does not seem to widespread known?

**Comment by themoosman** [comment]
It's not empty, just run `pip3 install -r requirements.txt ` per the instructions and it will work.

**Comment by Benehiko** [comment]
Hi @bmxp the `requirements.txt` uses the `setup.py` dependencies using a little hack to prevent us from duplicating packages to both files.

Please see this [SO thread](https://stackoverflow.com/questions/43658870/requirements-txt-vs-setup-py)

**Comment by bmxp** [comment]
Thanks for pointing this out. Unfortunately I did not find a clear statement in an official document like https://pip.pypa.io/en/stable/user_guide/ so I was irritated.
Well it works, this is fine but somethimes it's good to find a clear source for beginners like me
