### ISSUE TITLE
login error - is RLC-510a supported?

### ISSUE THREAD

**Issue by Helias** [ReolinkCameraAPI/reolinkapipy#60]
Hi, I tried to login using the following code:
```python
from reolinkapi.camera import Camera

ip: str = '127.0.0.1'
username: str = "admin"
password: str = "12345"
https: bool = True
defer_login: bool = False
profile: str = "main"

c = Camera(ip, username, password, https, defer_login, profile)
c.login()
```

and I get the following error
```json
[
   {
      "cmd" : "Login",
      "code" : 1,
      "error" : {
         "detail" : "param error",
         "rspCode" : -4
      }
   }
]
```

I am wondering if RLC-510a camera is supported, I don't see it in this issue https://github.com/ReolinkCameraAPI/reolinkapipy/issues/35

**Comment by Alexandre333** [comment]
Hi Helias, I had the same error code at first. I didn't open the corresponding port of my router for the camera, i followed this tutorial https://www.youtube.com/watch?v=KiqPcch8wK8&ab_channel=Reolink The

**Comment by themoosman** [comment]
I wonder if they changed the API in some of the newer cameras.

**Comment by Helias** [comment]
> Hi Helias, I had the same error code at first. I didn't open the corresponding port of my router for the camera, i followed this tutorial https://www.youtube.com/watch?v=KiqPcch8wK8&ab_channel=Reolink

Thanks! I will use it and let you know if it works.
if it works I could write how I did and close the issue

**Comment by themoosman** [comment]
There are so many things wrong with that video.  That said, this lib should work without opening ports on the firewall.  @Helias looking at your original code sample, that IP address you're using is wrong.

**Comment by Helias** [comment]
> 

You're right, I made it work with the code that I posted, I probably forgot something about https=True in the function parameters.

Thanks a lot, I solved it, now I am getting this issue.

![image](https://user-images.githubusercontent.com/519778/185674705-fb840e6c-d849-41c7-9d2c-cf3f62ede466.png)

**Comment by Helias** [comment]
I solved it NOT opening the port BUT enabling the TCP port inside the camera panel.
![image](https://user-images.githubusercontent.com/519778/185676668-e8929c5a-f7d5-4962-ad40-e2c60be01dc9.png)
