### ISSUE TITLE
get_snap incorrectly references random library

### ISSUE THREAD

**Issue by BenjaminPelletier** [ReolinkCameraAPI/reolinkapipy#61]
On line 39 of stream.py, the rs parameter is set as follows:

```python
'rs': ''.join(random.choices(string.ascii_uppercase + string.digits, k=10)),
```

However, the import statement on line 2 is

```python
from random import random
```

With this import statement, the symbol `random` refers to [the function](https://docs.python.org/3/library/random.html#random.random) rather than [the library](https://docs.python.org/3/library/random.html), and it is the library which has [the choices function](https://docs.python.org/3/library/random.html#random.choices).

This problem causes a crash with `AttributeError: 'builtin_function_or_method' object has no attribute 'choices'` when get_snap is called.

**Comment by BenjaminPelletier** [comment]
This was fixed in #50 11 months ago but is not in the most recent release 0.13.

**Comment by Benehiko** [comment]
Hi Benjamin,

Sorry about that, I will do another release as soon as I get some time.

In the meantime, you can install the latest from github directly

```shell
pip install git+https://github.com/ReolinkCameraAPI/reolinkapipy.git
```

**Comment by Benehiko** [comment]
Hi @BenjaminPelletier 

I have created a new release :)
https://pypi.org/project/reolinkapi/
